name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Optionally, you can build or run any code build steps here if needed
      # For example, if you have a Makefile:
      - name: Build project
        run: |
          source env/bin/activate
          make install
          make build

      - name: Run tests
        run: |
          source env/bin/activate
          make test
